### ISSUE TITLE
Organization README.md

### ISSUE THREAD

**Issue by aref-asadi** [MedX-Media/.github#1]
## Responsibility
@aref-asadi @Sinusealpha 

## Deadline
Forever

## Description
We should have an updated README about our organization to be well introduced.

## Tasks:

- [x] Create .github repository
- [x] Create profile directory
- [x] Create README.md
- [ ] Update README.md forever

**Comment by aref-asadi** [comment]
[README.md](https://github.com/MedX-Media/.github/blob/main/profile/README.md)
